// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getLikesCount = `-- name: GetLikesCount :one
SELECT COALESCE(
  (SELECT likes_count FROM likes WHERE dream_id = $1),
  0::bigint
)::bigint AS likes_count
`

func (q *Queries) GetLikesCount(ctx context.Context, dreamID string) (int64, error) {
	row := q.db.QueryRow(ctx, getLikesCount, dreamID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}

const incrementLikes = `-- name: IncrementLikes :one
INSERT INTO likes (dream_id, likes_count)
VALUES ($1, 1)
ON CONFLICT (dream_id)
DO UPDATE SET likes_count = likes.likes_count + 1
RETURNING likes_count
`

func (q *Queries) IncrementLikes(ctx context.Context, dreamID string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementLikes, dreamID)
	var likes_count int64
	err := row.Scan(&likes_count)
	return likes_count, err
}
